import {isTelegramLaunch,connectTelegram} from './telegram.js';
import {art} from './figma-art.js';
import {GAMES} from './config.js';
import {LEVELS,formatUZS} from './domain.js';
import {createDemoService} from './service.js';
import {icon,shield} from './icons.js';
const embedded=isTelegramLaunch(window.Telegram?.WebApp);
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),service=createDemoService();
let session=await service.getSession(),results=new Map(),busy=false,error=null,chat=[],scenario='normal',routeVersion=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=f=>`assets/${f}`;
const img=(f,alt='',cls='')=>`<img class="${cls}" src="${asset(f)}" alt="${esc(alt)}" decoding="async">`;
const route=()=>{const [page='home',id]=location.hash.slice(1).split('/');return {page:['home','games','levels','game','chat','ranking'].includes(page)?page:'home',id};};
const navItem=(href,name,ico,active)=>`<a class="nav-item ${active?'active':''}" href="#${href}" ${active?'aria-current="page"':''}>${icon(ico)}<span>${name}</span></a>`;
const title=(text,back='games')=>`<div class="page-title"><a class="back" aria-label="Orqaga" href="#${back}">${icon('back')}</a><h1 tabindex="-1">${text}</h1><span></span></div>`;
const badge=()=>`<span class="badge">${icon('people')} Demo ko‘rinish</span>`;
function home(){const rail=[GAMES[0],GAMES[6],GAMES[2],GAMES[7],GAMES[1],GAMES[3],GAMES[5],GAMES[4]];return `${badge()}<h1 class="welcome">Ilovaga xush kelibsiz,<br><em>Mehmon!</em></h1><div class="promo-rail" aria-label="O‘yinlar takliflari"><a class="promo" href="#game/lucky">${art('promo-lucky')}<strong>Lucky Jet o‘yini uchun demo signallarni ko‘ring</strong></a><a class="promo small" href="#game/chicken">${art('promo-chicken')}<strong>Chicken Road<br>Demo bilan tanishing</strong></a><a class="promo small" href="#game/chicken2">${art('promo-chicken2')}<strong>Chicken Road 2<br>Demo bilan tanishing</strong></a></div><div class="game-rail" aria-label="O‘yin tanlash"><a href="#games" class="game-shortcut"><span class="all-games">${art('thumb-all')}</span><span>O‘yinlar</span></a>${rail.map(g=>`<a class="game-shortcut" href="#game/${g.id}"><span class="shortcut-art">${['lucky','ice','thimbles','balloon'].includes(g.id)?art('thumb-'+g.id):img(g.icon||g.cover)}</span><span>${g.name}</span></a>`).join('')}</div><a href="#chat" class="feature">${art('chat-banner')}<div class="feature-content"><h2>Do‘stlar bilan suhbatlashing va tajriba almashing</h2><span class="mini-cta">Chatni ko‘rish</span></div></a><a href="#ranking" class="feature ranking-feature">${art('ranking-banner')}<div class="feature-content"><h2>Hamjamiyat reytingi va ishtirokchilar bilan tanishing</h2><span class="mini-cta">Top-100 ni ko‘rish</span></div></a><p class="fine-print">Demo — haqiqiy prognoz emas.</p>`;}
function games(){return `${badge()}<a href="#levels" class="level-summary">${shield(0)}<div><strong>Darajalar bilan tanishing</strong><p>Birinchi daraja uchun ${formatUZS(80000)}.<br>Kuniga 1 ta demo signal.</p><span class="text-link">Qanday darajalar mavjudligini ko‘rish</span></div></a><h1 class="section-title">O‘yinlar</h1><div class="game-grid">${GAMES.map(g=>`<a href="#game/${g.id}" class="game-card">${img(g.cover,g.name)}<div class="card-caption"><strong>${g.name}</strong><span class="demo-chip">DEMO</span></div></a>`).join('')}</div><p class="fine-print">Online va g‘oliblar statistikasi tasdiqlangan manba ulangandan keyin ko‘rsatiladi.</p>`;}
function levels(){return `${title('Darajalar')}<div class="level-hero">${art('levels-banner')}<div><h2>Oltin darajani oching!</h2><p>va barcha imkoniyatlar bilan tanishing</p></div></div><p class="level-copy">Quyida yangi darajalar va kunlik limitlar ko‘rsatilgan. Bu demo: darajani sinash to‘lov qilmaydi va haqiqiy hisobingizni o‘zgartirmaydi.</p><div class="levels">${LEVELS.map((l,i)=>`<section class="level-card ${session.levelId===l.id?'selected':''}">${shield(i)}<div><h2>${l.name}</h2><p>${l.dailyLimit===null?'Cheksiz demo signallar. Istalgan o‘yinni va natija ko‘rinishini kun davomida sinab ko‘ring. Bu namuna haqiqiy yutuqni bashorat qilmaydi.':`Kuniga ${l.dailyLimit} ta signal. Limit Toshkent vaqti bilan yangi kun boshlanganda yangilanadi.`}</p><p class="amount">Summa: ${formatUZS(l.price)}</p><button class="level-select" data-action="level" data-id="${l.id}" aria-label="${l.name}: demoda sinash">${session.levelId===l.id?'Demo: tanlangan':'Demoda sinash'}</button></div></section>`).join('')}</div><p class="fine-print">Demo: ${session.level.name} tanlangan. Haqiqiy kirish va to‘lov holati faqat server tomonidan tasdiqlanadi.</p>`;}
function stateBox(code){const data={OFFLINE:['Internet aloqasi yo‘q','Ulanishni tekshiring va qayta urinib ko‘ring.'],LIMIT:['Kunlik limit tugadi','Darajalarni ko‘ring yoki keyingi kunni kuting. Demo sozlamalarida hisobni qayta boshlash mumkin.'],UNAVAILABLE:['Natijani yuklab bo‘lmadi','Hozir natija mavjud emas. Iltimos, qayta urinib ko‘ring.']}[code]||['Xatolik yuz berdi','Iltimos, qayta urinib ko‘ring.'];return `<section class="state-box" role="alert"><h2>${data[0]}</h2><p>${data[1]}</p>${code==='LIMIT'?'<a class="primary" href="#levels">Darajalarni ko‘rish</a>':'<button class="primary" data-action="signal">Qayta urinish</button>'}</section>`;}
function resultView(g,r){let bg=g.result;if(g.id==='thimbles')bg=['thimbles-left.png','thimbles-center.png','thimbles-right.png'][r.value];return `<div class="result ${g.id}" role="status" aria-label="Demo natija: ${esc(r.label)}">${img(bg,'','bg')}${g.valueAsset?img(g.valueAsset,'','value-art'):g.id==='thimbles'?'':`<strong>${g.id==='balloon'?formatUZS(r.value):r.label.replace('.',',')}</strong>`}<span class="demo-chip">DEMO · NAMUNA</span></div>`;}
function game(id){const g=GAMES.find(g=>g.id===id);if(!g)return `${title('O‘yin topilmadi')}<a href="#games" class="primary">O‘yinlarga qaytish</a>`;const r=results.get(id);return `${title(g.name)}<div class="cover">${img(g.cover,g.name)}</div>${r?resultView(g,r):''}${error?stateBox(error):`<button class="primary" data-action="signal" ${busy?'disabled aria-busy="true"':''}>${busy?'<span class="spinner"></span> Yuklanmoqda…':r?'Yana demo signal olish':'Demo signal olish'}</button>`}<section class="instruction"><h2>Signalni qanday ishlataman?</h2><p>${g.name} o‘yinidagi demo natija qanday ko‘rsatilishini sinab ko‘ring. Bu namuna yutuqni bashorat qilmaydi.</p><button class="primary secondary" data-action="video">Videoni ko‘rish ${icon('video')}</button></section><div class="quota"><span>Demo: ${session.level.name} · ${session.remaining===null?'cheksiz':session.remaining+' ta qoldi'}</span><a href="#levels">Darajalar</a></div><p class="fine-print">Haqiqiy signallar faqat tekshirilgan manba ulangandan keyin mavjud bo‘ladi.</p>`;}
function chatView(){return `${badge()}<h1 class="section-title">Jonli chat</h1><p class="preview-note">Mahalliy demo. Xabarlar faqat ushbu sahifada ko‘rinadi; hech kimga yuborilmaydi.</p><section class="chat-frame"><div class="chat-messages" role="log" aria-live="polite">${chat.length?chat.map(m=>`<div class="chat-message"><strong>Siz · DEMO</strong><p>${esc(m)}</p></div>`).join(''):`<div class="chat-empty">${icon('chat')}<h2>Suhbat shu yerdan boshlanadi</h2><p>Chat ko‘rinishini sinash uchun xabar yozing. Haqiqiy chat hali ulanmagan.</p></div>`}</div><form class="chat-compose"><label class="sr-only" for="message">Xabaringiz</label><input id="message" name="message" placeholder="Xabar yozing…" maxlength="500" autocomplete="off" required><button aria-label="Demo xabarni qo‘shish">${icon('send')}</button></form></section>`;}
function ranking(){return `${badge()}<h1 class="section-title">${icon('trophy')} Top ishtirokchilar</h1><p class="preview-note">Reyting hozircha ulanmagan. Quyida faqat maket namunasi; foydalanuvchilar va yutuqlar statistikasi emas.</p><div class="podium">${[2,1,3].map(n=>`<div>${icon('trophy')}<small>Namuna ${n}</small><p>—</p></div>`).join('')}</div><div class="ranking-list">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<div class="rank-row"><span>#${n}</span><span>Demo profil ${n}</span><strong>—</strong></div>`).join('')}</div><p class="fine-print">Tasdiqlangan natijalar mavjud bo‘lganda reyting serverdan olinadi.</p>`;}
function render(){const {page,id}=route();const g=GAMES.find(g=>g.id===id);app.style.setProperty('--accent',g?.color||'#6b3fd4');const view={home,games,levels,game:()=>game(id),chat:chatView,ranking}[page];app.innerHTML=`${!navigator.onLine||scenario==='offline'?'<div class="offline" role="status">Internet aloqasi yo‘q · offline holat</div>':''}<main id="main-content" class="page-${page}"><div class="page-glow">${art('background')}</div>${view()}${!embedded?'<button class="demo-settings-link" data-action="settings">Demo sozlamalari</button>':''}</main><nav class="bottom-nav" aria-label="Asosiy navigatsiya">${navItem('home','Asosiy','home',page==='home')}${navItem('games','O‘yinlar','games',['games','game','levels'].includes(page))}${navItem('chat','Jonli Chat','chat',page==='chat')}${navItem('ranking','Top-100','trophy',page==='ranking')}</nav>`;}
function showDialog(body){modal.innerHTML=`<button class="dialog-close" data-action="dismiss" aria-label="Yopish">${icon('close')}</button>${body}`;const heading=modal.querySelector('h2');if(heading){heading.id='dialog-title';modal.setAttribute('aria-labelledby','dialog-title');}if(!modal.open)modal.showModal();}
function showSettings(){showDialog(`<h2>Demo sozlamalari</h2><p>Faqat mahalliy namuna. Haqiqiy hisob, to‘lov yoki server o‘zgarmaydi.</p><label>Demo darajasi<select id="demo-level">${LEVELS.map(l=>`<option value="${l.id}" ${session.levelId===l.id?'selected':''}>${l.name} · ${formatUZS(l.price)}</option>`).join('')}</select></label><label>Sinov holati<select id="demo-scenario">${[['normal','Oddiy'],['error','Server xatosi'],['offline','Internet yo‘q'],['limit','Limit tugagan']].map(([v,t])=>`<option value="${v}" ${scenario===v?'selected':''}>${t}</option>`).join('')}</select></label><button class="primary" data-action="apply-settings">Qo‘llash</button><button class="primary secondary" data-action="reset">Demoni qayta boshlash</button>`);}
async function signal(){if(busy)return;const {id,page}=route();if(page!=='game'||!GAMES.some(g=>g.id===id))return;if(!navigator.onLine){error='OFFLINE';render();return;}const version=routeVersion;busy=true;error=null;render();try{const r=await service.requestSignal(id,{idempotencyKey:crypto.randomUUID()});results.set(id,r);session=r.session;}catch(e){if(version===routeVersion)error=e.code||'UNAVAILABLE';}finally{busy=false;render();}}
async function handle(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='signal')return signal();if(a==='dismiss'){modal.close();return;}if(a==='settings')return showSettings();if(a==='video')return showDialog('<h2>Video qo‘llanma</h2><p>Ushbu o‘yin uchun tasdiqlangan video hali ulanmagan. Hozir demo tugmasi faqat oldindan belgilangan namunani ko‘rsatadi.</p><button class="primary secondary" data-action="dismiss">Tushunarli</button>');if(a==='about')return showDialog('<h2>Nexus AI · O‘zbekiston</h2><p>Figma asosidagi mahalliy demo. To‘lovlar, haqiqiy signallar, jonli chat va reyting ulanmagan. Natijalar yutuq va’dasi emas.</p><button class="primary" data-action="settings">Demo sozlamalari</button>');if(a==='close')return showDialog('<h2>Ko‘rishni yakunlash?</h2><p>Bu mahalliy ko‘rinish. Brauzer oynasini yopishingiz yoki ilovani ko‘rishda davom etishingiz mumkin.</p><button class="primary" data-action="dismiss">Davom etish</button>');if(a==='level'){session=await service.setLevel(b.dataset.id);error=null;render();return;}if(a==='apply-settings'){const chosenLevel=document.querySelector('#demo-level').value,chosenScenario=document.querySelector('#demo-scenario').value;b.disabled=true;session=await service.setLevel(chosenLevel);scenario=chosenScenario;service.setScenario(scenario);error=null;modal.close();render();return;}if(a==='reset'){session=await service.reset();scenario='normal';results.clear();chat=[];error=null;modal.close();render();}}
document.addEventListener('click',e=>{handle(e).catch(()=>{error='UNAVAILABLE';render();});});
document.addEventListener('submit',e=>{if(!e.target.matches('.chat-compose'))return;e.preventDefault();const text=new FormData(e.target).get('message').trim();if(text){chat.push(text.slice(0,500));render();document.querySelector('#message')?.focus();}});
window.addEventListener('hashchange',async()=>{routeVersion++;error=null;session=await service.getSession();render();const heading=app.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}window.scrollTo(0,0);});
window.addEventListener('offline',render);window.addEventListener('online',()=>{if(error==='OFFLINE')error=null;render();});
// UI integration only: no initData transmission, authorization or production requests.
const telegram=connectTelegram({tg:window.Telegram?.WebApp,app,getPage:()=>route().page,navigate:page=>{location.hash=page;},events:window,fallbackHeight:()=>window.innerHeight});
render();
telegram.ready();
