import {createSimulation} from './example-session.js?v=uz-minimal-20261008-193706';
import {exampleSection,mountExample} from './per-game-ui.js?v=uz-minimal-20261008-193706';
import {connectTelegram} from './telegram.js';
import {art} from './figma-art.js';
import {GAMES} from './config.js';
import {LEVELS,formatUZS} from './domain.js';
import {icon,shield} from './icons.js';
const app=document.querySelector('#app');
const cooldownStorage={getItem:key=>sessionStorage.getItem(key),setItem:(key,value)=>sessionStorage.setItem(key,value)};
const simulation=createSimulation({storage:cooldownStorage});
let unmountExample=()=>{};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=f=>`assets/${f}`;
const img=(f,alt='',cls='')=>`<img class="${cls}" src="${asset(f)}" alt="${esc(alt)}" decoding="async">`;
const route=()=>{const [page='home',id]=location.hash.slice(1).split('/');return {page:['home','games','levels','game','chat','ranking'].includes(page)?page:'home',id};};
const navItem=(href,name,ico,active)=>`<a class="nav-item ${active?'active':''}" href="#${href}" ${active?'aria-current="page"':''}>${icon(ico)}<span>${name}</span></a>`;
const title=(text,back='games')=>`<div class="page-title"><a class="back" aria-label="Orqaga" href="#${back}">${icon('back')}</a><h1 tabindex="-1">${text}</h1><span></span></div>`;
const badge=()=>`<span class="badge">${icon('people')} Nexus AI</span>`;
function home(){const rail=[GAMES[0],GAMES[6],GAMES[2],GAMES[7],GAMES[1],GAMES[3],GAMES[5],GAMES[4]];return `${badge()}<h1 class="welcome">Ilovaga xush kelibsiz,<br><em>Mehmon!</em></h1><div class="promo-rail" aria-label="O‘yinlar takliflari"><a class="promo" href="#game/lucky">${art('promo-lucky')}<strong>Lucky Jet o‘yini sahifasini oching</strong></a><a class="promo small" href="#game/chicken">${art('promo-chicken')}<strong>Chicken Road<br>O‘yin sahifasi</strong></a><a class="promo small" href="#game/chicken2">${art('promo-chicken2')}<strong>Chicken Road 2<br>O‘yin sahifasi</strong></a></div><div class="game-rail" aria-label="O‘yin tanlash"><a href="#games" class="game-shortcut"><span class="all-games">${art('thumb-all')}</span><span>O‘yinlar</span></a>${rail.map(g=>`<a class="game-shortcut" href="#game/${g.id}"><span class="shortcut-art">${['lucky','ice','thimbles','balloon'].includes(g.id)?art('thumb-'+g.id):img(g.icon||g.cover)}</span><span>${g.name}</span></a>`).join('')}</div><a href="#chat" class="feature">${art('chat-banner')}<div class="feature-content"><h2>Hamjamiyat uchun suhbat bo‘limi</h2><span class="mini-cta">Chatni ko‘rish</span></div></a><a href="#ranking" class="feature ranking-feature">${art('ranking-banner')}<div class="feature-content"><h2>Hamjamiyat reytingi</h2><span class="mini-cta">Top-100 ni ko‘rish</span></div></a><p class="fine-print">Xizmatlar hozircha ulanmagan.</p>`;}
function games(){return `${badge()}<a href="#levels" class="level-summary">${shield(0)}<div><strong>Darajalar bilan tanishing</strong><p>Birinchi daraja uchun ${formatUZS(80000)}.<br>Darajalar va limitlar tavsifi.</p><span class="text-link">Qanday darajalar mavjudligini ko‘rish</span></div></a><h1 class="section-title">O‘yinlar</h1><div class="game-grid">${GAMES.map(g=>`<a href="#game/${g.id}" class="game-card">${img(g.cover,g.name)}<div class="card-caption"><strong>${g.name}</strong></div></a>`).join('')}</div><p class="fine-print">Online va g‘oliblar statistikasi tasdiqlangan manba ulangandan keyin ko‘rsatiladi.</p>`;}
function levels(){return `${title('Darajalar')}<div class="level-hero">${art('levels-banner')}<div><h2>Darajalar bilan tanishing</h2><p>Imkoniyatlar va kunlik limitlar</p></div></div><p class="level-copy">Quyida darajalar tavsifi keltirilgan. Kirish va to‘lov xizmati hozircha ulanmagan. Hisobingiz uchun faollashtirilgan daraja ko‘rsatilmayapti.</p><div class="levels">${LEVELS.map((l,i)=>`<section class="level-card">${shield(i)}<div><h2>${l.name}</h2><p>${l.dailyLimit===null?'Kunlik limit: cheksiz.':`Kunlik limit: ${l.dailyLimit} ta signal.`}</p><p class="amount">Summa: ${formatUZS(l.price)}</p></div></section>`).join('')}</div><p class="fine-print">Darajani faollashtirish hozircha mavjud emas.</p>`;}
function game(id){const g=GAMES.find(g=>g.id===id);if(!g)return `${title('O‘yin topilmadi')}<a href="#games" class="primary">O‘yinlarga qaytish</a>`;return `${title(g.name)}<div class="cover">${img(g.cover,g.name)}</div>${exampleSection(id)}`;}
function chatView(){return `${badge()}<h1 class="section-title">Jonli chat</h1><section class="chat-frame"><div class="chat-messages"><div class="chat-empty">${icon('chat')}<h2>Chat hozircha ulanmagan</h2><p>Xabar yuborish hozircha mavjud emas.</p></div></div></section>`;}
function ranking(){return `${badge()}<h1 class="section-title">${icon('trophy')} Top ishtirokchilar</h1><section class="state-box"><h2>Reyting hozircha ulanmagan</h2><p>Tasdiqlangan natijalar mavjud emas.</p></section>`;}
function render(){unmountExample();const {page,id}=route();const g=GAMES.find(g=>g.id===id);app.style.setProperty('--accent',g?.color||'#6b3fd4');const view={home,games,levels,game:()=>game(id),chat:chatView,ranking}[page];app.innerHTML=`${!navigator.onLine?'<div class="offline" role="status">Internet aloqasi yo‘q · offline holat</div>':''}<main id="main-content" class="page-${page}"><div class="page-glow">${art('background')}</div>${view()}</main><nav class="bottom-nav" aria-label="Asosiy navigatsiya">${navItem('home','Asosiy','home',page==='home')}${navItem('games','O‘yinlar','games',['games','game','levels'].includes(page))}${navItem('chat','Jonli Chat','chat',page==='chat')}${navItem('ranking','Top-100','trophy',page==='ranking')}</nav>`;unmountExample=mountExample(app.querySelector('.game-example'),page==='game'?id:null,simulation);}
window.addEventListener('hashchange',()=>{render();const heading=app.querySelector('h1');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}window.scrollTo(0,0);});
window.addEventListener('offline',render);window.addEventListener('online',render);
// UI integration only: no initData transmission, authorization or production requests.
const telegram=connectTelegram({tg:window.Telegram?.WebApp,app,getPage:()=>route().page,navigate:page=>{location.hash=page;},events:window,fallbackHeight:()=>window.innerHeight});
render();
telegram.ready();
